wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=r8yvpE7HivnKv5k
     - WORDPRESS_DB_USER=wordpress
    ports:
     - "public_ip:80:80"
    volumes:
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=r8yvpE7HivnKv5k
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
